# Generated by Django 4.1.7 on 2024-07-28 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_order_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FeaturedFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='featured', to='base.food')),
            ],
        ),
    ]
